# Hexo 配置  # Hexo Configuration
## 文档: https://hexo.io/docs/configuration.html  # Docs: https://hexo.io/docs/configuration.html
## 源码: https://github.com/hexojs/hexo/  # Source: https://github.com/hexojs/hexo/

# 站点信息  # Site
title: Sleep3r_blog  # 网站标题
subtitle: '想成为二进制博主'  # 网站副标题
description: ''  # 网站描述
keywords:  # 网站关键词
author: Sleep3r  # 作者
language: zh  # 语言
timezone: ''  # 时区

# URL 设置  # URL
## 在这里设置你的网站地址。例如，如果你使用 GitHub Page，将 url 设置为 'https://username.github.io/project'  # Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://example.com  # 网站地址
permalink: :year/:month/:day/:title/  # 文章永久链接格式
permalink_defaults:  # 永久链接默认值
pretty_urls:  # 美化 URL
  trailing_index: true # 设为 false 可移除永久链接中的 'index.html'  # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # 设为 false 可移除永久链接中的 '.html'  # Set to false to remove trailing '.html' from permalinks

# 目录设置  # Directory
source_dir: source  # 资源文件夹
public_dir: public  # 生成的静态文件夹
tag_dir: tags  # 标签文件夹
archive_dir: archives  # 归档文件夹
category_dir: categories  # 分类文件夹
code_dir: downloads/code  # 代码文件夹
i18n_dir: :lang  # 多语言文件夹
skip_render:  # 跳过渲染的文件

# 写作设置  # Writing
new_post_name: :title.md # 新文章的文件名  # File name of new posts
default_layout: post  # 默认布局
titlecase: false # 标题是否转换为标题格式  # Transform title into titlecase
external_link:  # 外部链接设置
  enable: true # 是否在新标签页打开外部链接  # Open external links in new tab
  field: site # 应用于整个站点  # Apply to the whole site
  exclude: '' # 排除的链接  # Exclude
filename_case: 0  # 文件名大小写（0: 保持原样, 1: 全小写, 2: 全大写）
render_drafts: false  # 是否渲染草稿
post_asset_folder: false  # 是否为每篇文章使用单独的资源文件夹
relative_link: false  # 是否使用相对链接
future: true  # 是否显示未来的文章
syntax_highlighter: highlight.js  # 语法高亮器
highlight:  # highlight.js 配置
  line_number: true  # 显示行号
  auto_detect: false  # 自动检测语言
  tab_replace: ''  # 替换 tab 字符
  wrap: true  # 自动换行
  hljs: false  # 是否使用 highlight.js 的样式
prismjs:  # prismjs 配置
  preprocess: true  # 预处理
  line_number: true  # 显示行号
  tab_replace: ''  # 替换 tab 字符

# 首页设置  # Home page setting
# path: 博客首页的根路径 (默认 = '')  # path: Root path for your blogs index page. (default = '')
# per_page: 每页显示的文章数 (0 = 不分页)  # per_page: Posts displayed per page. (0 = disable pagination)
# order_by: 文章排序方式 (默认按日期降序)  # order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''  # 首页路径
  per_page: 10  # 每页文章数
  order_by: -date  # 排序方式

# 分类与标签  # Category & Tag
default_category: uncategorized  # 默认分类
category_map:  # 分类映射
tag_map:  # 标签映射

# 元数据元素  # Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta  # 参考链接
meta_generator: true  # 是否生成 meta 标签

# 日期/时间格式  # Date / Time format
## Hexo 使用 Moment.js 解析和显示日期  # Hexo uses Moment.js to parse and display date
## 你可以自定义日期格式，参考  # You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/  # 参考链接
date_format: YYYY-MM-DD  # 日期格式
time_format: HH:mm:ss  # 时间格式
## updated_option 支持 'mtime', 'date', 'empty'  # updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'  # 更新时间选项

# 分页设置  # Pagination
## 设置 per_page 为 0 可禁用分页  # Set per_page to 0 to disable pagination
per_page: 10  # 每页文章数
pagination_dir: page  # 分页目录

# 包含/排除文件  # Include / Exclude file(s)
## include:/exclude: 选项仅适用于 'source/' 文件夹  # include:/exclude: options only apply to the 'source/' folder
include:  # 包含的文件
exclude:  # 排除的文件
ignore:  # 忽略的文件

# 扩展  # Extensions
## 插件: https://hexo.io/plugins/  # Plugins: https://hexo.io/plugins/
## 主题: https://hexo.io/themes/  # Themes: https://hexo.io/themes/
theme: butterfly  # 当前主题

# 部署  # Deployment
## 文档: https://hexo.io/docs/one-command-deployment  # Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''  # 部署类型
